/-
Copyright (c) 2026. Released under Apache 2.0.
Authors: JSP-000087 formalization (Yi-131-a).
-/
import JSPProblem.TcVariance
import JSPProblem.EulerDivergence
import Mathlib.Tactic

/-!
# JSP-000087, round 131 — THE SHIFT-PARAMETRISED CORRELATIONS AND THE SIGN-FREE
# VARIANCE SANDWICH

## Why this file exists

Round 130 (`JSPProblem/TcVariance.lean`) computed the **exact** second moment of
the truncated carry of Tao–Teräväinen (arXiv:2512.01739, §5.4), split it into
the arithmetic diagonal `jsp87TcDiag` and the **weighted sum of two-point
correlations** `jsp87TcOff`, and identified the missing analytic input as a
small bound on the covariances `jsp87Mcov L k k'`.  Its two transfer lemmas

* `jsp87TcVar_ge_diag` — needs `0 ≤ jsp87Mcov` at every pair, and
* `jsp87TcVar_le_diag_add` — needs `jsp87Mcov ≤ ε` at every pair,

**both carry a sign hypothesis on the covariances**, and the first one is
vacuous if a single covariance is negative.  That is exactly the kind of
hypothesis the published proof has to *establish*, and round 130 could not.

**This file removes the sign hypothesis.**  §3 proves the Cauchy–Schwarz bound
on the covariances — `|Cov| ≤ σ_k σ_k'` — **from the discriminant argument of
round 130's `jsp87CS`**, with no analytic input whatsoever, and §5 turns it into
the sign-free sandwich

```
Σ_k 4^{-(k+1)} Var (ω(N+k))  −  M   ≤   Var (N ↦ T(N,H))
                                ≤   Σ_k 4^{-(k+1)} Var (ω(N+k))  +  ε
```

for **any** `ε ≥ 0` and **any** `M` dominating the marginal variances.  So §5.4
of arXiv:2512.01739 is now reduced to the two *scalar* bounds it really needs,
with **no positivity assumption on the correlations**.

§1 executes `policy.json` `next_round_attack[0]` of round 130: the correlation at
the shift pair `(k, k+d)` is the shift-`d` correlation plus a boundary term with
exactly `k` elements, **as an identity** — so the `H (H−1)/2` correlation inputs
of §5.4 are generated by `H` shifts and a boundary error `O(k (log L)²)`.

§2 is the arithmetic content of the shift dependence: the pairs `(p, q)` with
`p = q` in `ω m · ω (m+d)` are exactly the prime divisors of `gcd m d`, so a
correlation splits into a shift-dependent part (`≤ L · ω d`) and a shift-free
part (pairs of *distinct* primes).  `jsp87CorrShift_ge_firstMoment` then gives
the first lower bound on a correlation in the tree: the Chowla-type sum is
`≳ L · log log L` (Euler's divergence, unconditional).

## What this does NOT do

`jsp_000087_main` remains undeclared.  Nothing here supplies the Chowla/Elliott
type **upper** bound on `jsp87Mcov` (arXiv:2512.01739 Thm 3.1), which Mathlib
does not contain; what is proved is that the covariance input of §5.4 is
*bounded below* as well as above, and that its sign is irrelevant.
-/

namespace JSP87

open scoped BigOperators

set_option maxHeartbeats 1000000

/-! ## 0. The objects -/

/-- **THE CORRELATION OF `ω` WITH ITSELF AT THE SHIFT `d`**, over the window
`[0, L)`: `∑_{m<L} ω m · ω (m+d)`.  `d = 0` is the second moment, `d = 1` is the
Chowla sum of `ω`, and `d = k' − k` is (up to the boundary) what
`jsp87CorrAt L k k'` of round 130 measures. -/
def jsp87CorrShift (d L : ℕ) : ℕ := ∑ m ∈ Finset.range L, omega m * omega (m + d)

/-- **THE BOUNDARY TERM** of the shift parametrisation: the shift-`d`
correlation over `[0, k)`, which has exactly `k` elements — one per place that
was shifted out of the window. -/
def jsp87CorrCut (k d : ℕ) : ℕ := ∑ m ∈ Finset.range k, omega m * omega (m + d)

/-- **THE COMMON-PRIME CONTENT** of the correlation at shift `d`:
`∑_{m<L} ω (gcd m d)` — the number of pairs `(m, p)` with `p` a prime dividing
both `m` and `m + d`, i.e. dividing `d`.  This is the only *degenerate* way in
which a correlation can depend on the shift. -/
def jsp87CorrGcd (d L : ℕ) : ℕ := ∑ m ∈ Finset.range L, omega (Nat.gcd m d)

/-- **THE STANDARD DEVIATION OF THE TRUNCATED CARRY'S MARGINAL**: `σ_k`. -/
noncomputable def jsp87TcStd (L k : ℕ) : ℝ := Real.sqrt (jsp87TcVarAt L k)

/-- **`ω` IS AT MOST THE LOGARITHM OF ITS ARGUMENT, EVERYWHERE.** -/
theorem omega_le_log2_all (n : ℕ) : omega n ≤ Nat.log 2 n := by
  rcases Nat.eq_zero_or_pos n with h | h
  · rw [h, omega_zero]
    simp
  · exact omega_le_log2 h

/-! ## 1. THE SHIFT-PARAMETRISATION (`next_round_attack[0]` of round 130) -/

private theorem jsp87_sum_shift (f : ℕ → ℕ) (k L : ℕ) :
    (∑ N ∈ Finset.range L, f (N + k)) = ∑ m ∈ Finset.Ico k (L + k), f m := by
  induction L with
  | zero => simp
  | succ L ih =>
    have h1 : (∑ N ∈ Finset.range (L + 1), f (N + k))
        = (∑ N ∈ Finset.range L, f (N + k)) + f (L + k) := by
      exact Finset.sum_range_succ (fun N => f (N + k)) L
    have h2 : (∑ m ∈ Finset.Ico k (L + k + 1), f m)
        = (∑ m ∈ Finset.Ico k (L + k), f m) + f (L + k) := by
      exact Finset.sum_Ico_succ_top (a := k) (b := L + k) (by omega) f
    have h3 : (L + 1 + k) = (L + k + 1) := by omega
    rw [h1, h3, h2, ih]

/-- **THE SHIFT-PARAMETRISATION OF THE CORRELATIONS — THE HEADLINE OF §1.**

For every `k, d, L`, the correlation of `ω` at the shift pair `(k, k+d)` is the
shift-`d` correlation over the window `[0, L+k)` **plus** the shift-`d`
correlation over `[0, k)`, which is a boundary term with exactly `k` elements:

```
jsp87CorrAt L k (k + d) + jsp87CorrShift d k = jsp87CorrShift d (L + k) .
```

This is an **identity**, so the `H (H−1)/2` correlation inputs of §5.4 of
arXiv:2512.01739 (round 130, `jsp87TcOff`) are generated by the `H` shift
correlations `1 ≤ d < H` — precisely what `policy.json`
`next_round_attack[0]` asked for. -/
theorem jsp87CorrAt_shiftEq (k d L : ℕ) :
    jsp87CorrAt L k (k + d) + jsp87CorrCut k d = jsp87CorrShift d (L + k) := by
  have hA : (∑ N ∈ Finset.range L, omega (N + k) * omega (N + k + d))
      = ∑ m ∈ Finset.Ico k (L + k), omega m * omega (m + d) :=
    jsp87_sum_shift (fun t => omega t * omega (t + d)) k L
  have hC : (∑ m ∈ Finset.Ico k (L + k), omega m * omega (m + d))
      + ∑ m ∈ Finset.range k, omega m * omega (m + d)
      = ∑ m ∈ Finset.range (L + k), omega m * omega (m + d) := by
    have h := Finset.sum_Ico_consecutive (fun t => omega t * omega (t + d))
      (m := 0) (n := k) (k := L + k) (Nat.zero_le _) (by omega)
    rw [Nat.Ico_zero_eq_range (L + k), Nat.Ico_zero_eq_range k,
      add_comm] at h
    exact h
  have hD : (∑ m ∈ Finset.range (L + k), omega m * omega (m + d))
      = jsp87CorrShift d (L + k) := by rfl
  have hE : (∑ m ∈ Finset.range k, omega m * omega (m + d))
      = jsp87CorrCut k d := by rfl
  simp only [Nat.add_assoc] at hA
  unfold jsp87CorrAt
  rw [hA, ← hE, hC, hD]

/-- **THE SHIFTED CORRELATION IS AT MOST THE SHIFT CORRELATION OF THE ENLARGED
WINDOW** — the usable form of §1: every one of the `H (H−1)/2` correlation
inputs of §5.4 is bounded by one of the `H` shift correlations
`jsp87CorrShift d (L + k)`, `1 ≤ d < H`. -/
theorem jsp87CorrAt_le_shift (k d L : ℕ) :
    jsp87CorrAt L k (k + d) ≤ jsp87CorrShift d (L + k) := by
  have h := jsp87CorrAt_shiftEq k d L
  have hc : jsp87CorrCut k d = jsp87CorrShift d k := by rfl
  rw [hc] at h
  calc jsp87CorrAt L k (k + d)
      ≤ jsp87CorrAt L k (k + d) + jsp87CorrShift d k := Nat.le_add_right _ _
    _ = jsp87CorrShift d (L + k) := h

/-- **THE SHIFT PARAMETRISATION, SHARPENED: THE BOUNDARY ERROR IS THE SMALLER
WINDOW.**  Since `jsp87CorrShift d k ≤ jsp87CorrShift d (L + k)`, the number of
*distinct analytic inputs* of §5.4 is `H`, not `H (H−1)/2`. -/
theorem jsp87CorrShift_mono_window (d k L : ℕ) (_h : k ≤ L) :
    jsp87CorrShift d k ≤ jsp87CorrShift d (L + k) := by
  unfold jsp87CorrShift
  apply Finset.sum_le_sum_of_subset_of_nonneg
  · intro m hm
    rw [Finset.mem_range] at hm ⊢
    omega
  · intro m _ hm
    exact Nat.zero_le _

/-- **THE BOUNDARY TERM IS `O(k · (log L)²)`.**  This is the price of moving a
window by `k` places, and it is the size of the error term in the shift
parametrisation of §1. -/
theorem jsp87CorrCut_le_log (k d : ℕ) :
    jsp87CorrCut k d ≤ k * Nat.log 2 (k + d + 1) * Nat.log 2 (k + d + 1) := by
  have hterm : ∀ m ∈ Finset.range k,
      omega m * omega (m + d) ≤ Nat.log 2 (k + d + 1) * Nat.log 2 (k + d + 1) := by
    intro m hm
    have hm' : m < k := Finset.mem_range.mp hm
    have h1 : omega m ≤ Nat.log 2 m := omega_le_log2_all m
    have h2 : Nat.log 2 m ≤ Nat.log 2 (k + d + 1) := by
      apply Nat.log_mono_right
      omega
    have h3 : omega (m + d) ≤ Nat.log 2 (m + d) := omega_le_log2_all (m + d)
    have h4 : Nat.log 2 (m + d) ≤ Nat.log 2 (k + d + 1) := by
      apply Nat.log_mono_right
      omega
    exact Nat.mul_le_mul (le_trans h1 h2) (le_trans h3 h4)
  unfold jsp87CorrCut
  calc (∑ m ∈ Finset.range k, omega m * omega (m + d))
      ≤ ∑ _m ∈ Finset.range k,
          Nat.log 2 (k + d + 1) * Nat.log 2 (k + d + 1) := Finset.sum_le_sum hterm
    _ = (Finset.range k).card
        * (Nat.log 2 (k + d + 1) * Nat.log 2 (k + d + 1)) := by
        rw [Finset.sum_const, Nat.nsmul_eq_mul]
    _ ≤ k * (Nat.log 2 (k + d + 1) * Nat.log 2 (k + d + 1)) := by
        rw [Finset.card_range]
    _ = k * Nat.log 2 (k + d + 1) * Nat.log 2 (k + d + 1) := by ring

/-! ## 2. THE COMMON-PRIME (GCD) CONTENT OF A CORRELATION -/

/-- **THE PRODUCT OF THE `ω`-VALUES DOMINATES THE COMMON-PRIME COUNT.**

`ω a · ω b ≥ ω (gcd a b)`: among the ordered pairs `(p, q)` with `p ∣ a`,
`q ∣ b` sit the diagonal pairs `p = q`, which are indexed by the common prime
divisors, i.e. by `gcd a b`.  Mathlib has no such statement; `omega_mono` plus
`Nat.le_mul_of_pos_right` suffice. -/
theorem omega_mul_ge_gcd {a b : ℕ} (ha : 0 < a) (hb : 0 < b) :
    omega (Nat.gcd a b) ≤ omega a * omega b := by
  by_cases hb1 : b ≤ 1
  · have hgb : omega (Nat.gcd a b) ≤ omega b :=
      omega_mono (Nat.gcd_dvd_right a b) hb.ne'
    have h0 : omega b = 0 := (omega_eq_zero_iff).mpr hb1
    rw [h0]
    omega
  · have hb2 : 0 < omega b := by
      by_contra hcon
      have h0 : omega b = 0 := Nat.eq_zero_of_not_pos hcon
      have hb' : b ≤ 1 := (omega_eq_zero_iff).mp h0
      omega
    exact le_trans (omega_mono (Nat.gcd_dvd_left a b) ha.ne')
      (Nat.le_mul_of_pos_right _ hb2)

/-- **THE COMMON-PRIME CONTENT IS BOUNDED BY THE `ω`-VALUE OF THE SHIFT.**
`ω (gcd m d) ≤ ω d` for every `m`, so the shift-dependent part of a correlation
at shift `d` is at most `L · ω d`. -/
theorem omega_gcd_le (d m : ℕ) (hd : 1 ≤ d) : omega (Nat.gcd m d) ≤ omega d := by
  rcases Nat.eq_zero_or_pos m with hm | hm
  · rw [hm, Nat.gcd_comm, Nat.gcd_zero_right]
  · exact omega_mono (by rw [Nat.gcd_comm]; exact Nat.gcd_dvd_left d m) (by omega)

theorem jsp87CorrGcd_le_mul {d L : ℕ} (hd : 1 ≤ d) :
    ((jsp87CorrGcd d L : ℕ) : ℝ) ≤ (L : ℝ) * (omega d : ℝ) := by
  have hterm : ∀ m ∈ Finset.range L,
      ((omega (Nat.gcd m d) : ℕ) : ℝ) ≤ (omega d : ℝ) := by
    intro m hm
    exact_mod_cast omega_gcd_le d m hd
  calc ((jsp87CorrGcd d L : ℕ) : ℝ)
      = ∑ m ∈ Finset.range L, ((omega (Nat.gcd m d) : ℕ) : ℝ) := by
          unfold jsp87CorrGcd
          exact_mod_cast rfl
    _ ≤ ∑ _m ∈ Finset.range L, (omega d : ℝ) := Finset.sum_le_sum hterm
    _ = (omega d : ℝ) * ((Finset.range L).card : ℕ) := by
        rw [Finset.sum_const, nsmul_eq_mul]
        ring
    _ = (L : ℝ) * (omega d : ℝ) := by rw [jsp87cast_card_range L]; ring

/-- **THE CORRELATION, WITH THE `m = 0` TERM REMOVED.**  For `1 ≤ L`,
`jsp87CorrShift d L = ∑_{1 ≤ m < L} ω m · ω (m + d)`, because `ω 0 = 0`.  This is
the window on which the arithmetic of §2 is honest (`m = 0` is a prime divisor of
every integer). -/
theorem jsp87CorrShift_eq_Icc {d L : ℕ} (hL : 1 ≤ L) :
    (jsp87CorrShift d L : ℕ) = ∑ m ∈ Finset.Icc 1 (L - 1), omega m * omega (m + d) := by
  have hr : Finset.range L = insert 0 (Finset.Icc 1 (L - 1)) := by
    ext k
    simp only [Finset.mem_range, Finset.mem_insert, Finset.mem_Icc]
    omega
  have hn0 : (0 : ℕ) ∉ Finset.Icc 1 (L - 1) := by simp
  unfold jsp87CorrShift
  rw [hr, Finset.sum_insert hn0]
  simp [omega_zero]

/-- **THE CORRELATION DOMINATES ITS COMMON-PRIME CONTENT**, up to the single
endpoint term `ω d` contributed by `m = 0` (where every prime divides `0`):

```
∑_{1 ≤ m < L} ω m · ω (m + d)   ≥   ∑_{m < L} ω (gcd m d)  −  ω d .
```

So the shift-dependent part of a correlation is a *lower-order* object: it is
counted by the prime divisors of the shift, and §2.4 bounds it by `L · ω d`. -/
theorem jsp87CorrShift_ge_gcd {d L : ℕ} (hL : 1 ≤ L) :
    ((jsp87CorrShift d L : ℕ) : ℝ) + (omega d : ℝ) ≥ ((jsp87CorrGcd d L : ℕ) : ℝ) := by
  have hr : Finset.range L = insert 0 (Finset.Icc 1 (L - 1)) := by
    ext k
    simp only [Finset.mem_range, Finset.mem_insert, Finset.mem_Icc]
    omega
  have hn0 : (0 : ℕ) ∉ Finset.Icc 1 (L - 1) := by simp
  have hterm : ∀ m ∈ Finset.Icc 1 (L - 1),
      ((omega (Nat.gcd m d) : ℕ) : ℝ) ≤ ((omega m * omega (m + d) : ℕ) : ℝ) := by
    intro m hm
    have hm1 : 1 ≤ m := (Finset.mem_Icc.mp hm).1
    have hmono : omega (Nat.gcd m d) ≤ omega (Nat.gcd m (m + d)) := by
      have hdiv : Nat.gcd m d ∣ Nat.gcd m (m + d) :=
        Nat.dvd_gcd (Nat.gcd_dvd_left m d)
          (Nat.dvd_add (Nat.gcd_dvd_left m d)
            (by rw [Nat.gcd_comm]; exact Nat.gcd_dvd_left d m))
      exact_mod_cast omega_mono hdiv
        (Nat.gcd_pos_of_pos_left (m + d) (by omega)).ne'
    have hle : omega (Nat.gcd m (m + d)) ≤ omega m * omega (m + d) :=
      omega_mul_ge_gcd (by omega) (by omega)
    exact_mod_cast le_trans hmono hle
  have hsum : ((jsp87CorrShift d L : ℕ) : ℝ)
      = ∑ m ∈ Finset.Icc 1 (L - 1), ((omega m * omega (m + d) : ℕ) : ℝ) := by
    rw [jsp87CorrShift_eq_Icc hL]
    exact_mod_cast rfl
  have hg2 : (∑ m ∈ Finset.Icc 1 (L - 1), ((omega (Nat.gcd m d) : ℕ) : ℝ))
      = ((jsp87CorrGcd d L : ℕ) : ℝ) - (omega d : ℝ) := by
    unfold jsp87CorrGcd
    rw [hr, Finset.sum_insert hn0]
    simp [Nat.gcd_comm, Nat.gcd_zero_right]
  have hge : ∑ m ∈ Finset.Icc 1 (L - 1), ((omega m * omega (m + d) : ℕ) : ℝ)
      ≥ ∑ m ∈ Finset.Icc 1 (L - 1), ((omega (Nat.gcd m d) : ℕ) : ℝ) :=
    Finset.sum_le_sum hterm
  rw [hsum] at ⊢
  rw [hg2] at hge
  linarith

/-! ## 3. THE COVARIANCE AS AN AVERAGE OF THE CENTRED PRODUCT -/

/-- **THE SUM OF THE CENTRED PRODUCT.** -/
private theorem jsp87_sum_center {iℕ : Type*} (s : Finset iℕ) (a b : ℝ) (f g : iℕ → ℝ) :
    (∑ N ∈ s, ((f N - a) * (g N - b)))
      = (∑ N ∈ s, (f N * g N)) - (∑ N ∈ s, (f N)) * b
        - a * (∑ N ∈ s, (g N)) + ((s.card : ℕ) : ℝ) * (a * b) := by
  have hkey : ∀ N : iℕ, (f N - a) * (g N - b)
      = ((f N - a) * g N - (f N - a) * b) := by
    intro N; ring
  have hkey2 : ∀ N : iℕ, (f N - a) * b = (f N * b - a * b) := by
    intro N; ring
  have hkey3 : ∀ N : iℕ, (f N - a) * g N = (f N * g N - a * g N) := by
    intro N; ring
  calc (∑ N ∈ s, ((f N - a) * (g N - b)))
      = ∑ N ∈ s, (((f N - a) * g N - (f N - a) * b)) := by
        simp_rw [hkey]
    _ = (∑ N ∈ s, ((f N * g N - a * g N)))
          - ∑ N ∈ s, ((f N * b - a * b)) := by
        rw [Finset.sum_sub_distrib]
        simp_rw [hkey3, hkey2]
    _ = ((∑ N ∈ s, (f N * g N)) - ∑ N ∈ s, ((a * g N)))
          - ((∑ N ∈ s, (f N * b)) - ∑ N ∈ s, (a * b)) := by
        rw [Finset.sum_sub_distrib, Finset.sum_sub_distrib]
    _ = ((∑ N ∈ s, (f N * g N)) - a * (∑ N ∈ s, (g N)))
          - ((∑ N ∈ s, (f N)) * b - ((s.card : ℕ) : ℝ) * (a * b)) := by
        rw [Finset.mul_sum (s := s) (fun N => g N) a,
          Finset.sum_const, nsmul_eq_mul, Finset.sum_mul]
    _ = _ := by ring

private theorem jsp87_FAvg_center {iℕ : Type*} (s : Finset iℕ) (hs : s.Nonempty)
    (f g : iℕ → ℝ) :
    jsp87FAvg s (fun N => (f N - jsp87FAvg s f) * (g N - jsp87FAvg s g))
      = jsp87FAvg s (fun N => f N * g N) - jsp87FAvg s f * jsp87FAvg s g := by
  have hc : ((s.card : ℕ) : ℝ) ≠ 0 := by
    exact_mod_cast Finset.card_ne_zero.mpr hs
  have h1 : (∑ N ∈ s, (f N - (∑ i ∈ s, f i) / ((s.card : ℕ) : ℝ))
            * (g N - (∑ i ∈ s, g i) / ((s.card : ℕ) : ℝ)))
      = (∑ N ∈ s, f N * g N)
        - (∑ N ∈ s, f N) * ((∑ i ∈ s, g i) / ((s.card : ℕ) : ℝ))
        - ((∑ i ∈ s, f i) / ((s.card : ℕ) : ℝ)) * (∑ N ∈ s, g N)
        + ((s.card : ℕ) : ℝ) * (((∑ i ∈ s, f i) / ((s.card : ℕ) : ℝ))
            * ((∑ i ∈ s, g i) / ((s.card : ℕ) : ℝ))) :=
    jsp87_sum_center s _ _ f g
  calc jsp87FAvg s (fun N => (f N - jsp87FAvg s f) * (g N - jsp87FAvg s g))
      = ((∑ N ∈ s, f N * g N) - (∑ N ∈ s, f N) * jsp87FAvg s g
          - jsp87FAvg s f * (∑ N ∈ s, g N)
          + ((s.card : ℕ) : ℝ) * (jsp87FAvg s f * jsp87FAvg s g))
          / ((s.card : ℕ) : ℝ) := by
        unfold jsp87FAvg
        rw [h1]
    _ = jsp87FAvg s (fun N => f N * g N) - jsp87FAvg s f * jsp87FAvg s g := by
        unfold jsp87FAvg
        field_simp
        ring

/-- **THE COVARIANCE OF TWO SHIFTS OF `ω` IS THE AVERAGE OF THE CENTRED
PRODUCT.** -/
theorem jsp87Mcov_eq_FAvg (L k k' : ℕ) (hL : 1 ≤ L) :
    jsp87Mcov L k k'
      = jsp87FAvg (Finset.range L)
          (fun N => (((omega (N + k) : ℕ) : ℝ) - jsp87TcMean L k)
            * (((omega (N + k') : ℕ) : ℝ) - jsp87TcMean L k')) := by
  show jsp87TcCorr L k k' - jsp87TcMean L k * jsp87TcMean L k' = _
  exact (jsp87_FAvg_center (Finset.range L) ⟨0, Finset.mem_range.mpr hL⟩
    (fun N => ((omega (N + k) : ℕ) : ℝ)) (fun N => ((omega (N + k') : ℕ) : ℝ))).symm

/-- **THE CENTRED SECOND MOMENT OF A FINITE AVERAGE IS ITS VARIANCE TIMES THE
NUMBER OF SAMPLES.** -/
private theorem jsp87_sq_centred_key (s : Finset ℕ) (g : ℕ → ℝ) :
    (∑ N ∈ s, (g N - jsp87FAvg s g) ^ 2)
      = ((s.card : ℕ) : ℝ) * jsp87FAvg s (fun N => (g N - jsp87FAvg s g) ^ 2) := by
  by_cases hs0 : s.card = 0
  · have hnil : s = ∅ := Finset.card_eq_zero.mp hs0
    simp [hnil, jsp87FAvg]
  · have hc : ((s.card : ℕ) : ℝ) ≠ 0 := by
      have hpos : 0 < s.card := Nat.pos_of_ne_zero hs0
      exact_mod_cast hpos.ne'
    unfold jsp87FAvg
    field_simp
    refine Finset.sum_congr rfl fun N _ => ?_
    ring

/-- **THE CENTRED SECOND MOMENT IS THE VARIANCE TIMES THE WINDOW LENGTH.** -/
theorem jsp87_sq_centred (L k : ℕ) :
    (∑ N ∈ Finset.range L,
        (((omega (N + k) : ℕ) : ℝ) - jsp87TcMean L k) ^ 2)
      = (L : ℝ) * jsp87TcVarAt L k := by
  unfold jsp87TcMean jsp87TcVarAt jsp87Var
  have hk := jsp87_sq_centred_key (Finset.range L) (fun N => ((omega (N + k) : ℕ) : ℝ))
  rw [jsp87cast_card_range L] at hk
  exact hk

/-- **CAUCHY–SCHWARZ FOR THE COVARIANCES — THE SQUARED FORM, THE MAIN
THEOREM OF §3.**

```
Cov (ω(N+k), ω(N+k'))²  ≤  Var (ω(N+k)) · Var (ω(N+k')) .
```

This is Cauchy–Schwarz (round 130's `jsp87CS`, from the discriminant argument)
applied to the two *centred* functions, and **no analytic input at all**: it is
the sign-free replacement for round 130's `jsp87TcVar_ge_diag`, whose hypothesis
`0 ≤ jsp87Mcov` was not available. -/
theorem jsp87Mcov_sq_le_var (L k k' : ℕ) (hL : 1 ≤ L) :
    jsp87Mcov L k k' ^ 2 ≤ jsp87TcVarAt L k * jsp87TcVarAt L k' := by
  have hCS := jsp87CS (Finset.range L)
    (fun N => (((omega (N + k) : ℕ) : ℝ) - jsp87TcMean L k))
    (fun N => (((omega (N + k') : ℕ) : ℝ) - jsp87TcMean L k'))
  rw [jsp87_sq_centred L k, jsp87_sq_centred L k'] at hCS
  rw [jsp87Mcov_eq_FAvg L k k' hL, jsp87FAvg, jsp87cast_card_range, div_pow]
  have hLpos : (0 : ℝ) < (L : ℝ) ^ 2 := by positivity
  refine (div_le_iff₀ hLpos).2 ?_
  nlinarith [hCS]

/-- **CAUCHY–SCHWARZ FOR THE COVARIANCES — THE ABSOLUTE-VALUE FORM.** -/
theorem jsp87Mcov_abs_le_std (L k k' : ℕ) (hL : 1 ≤ L) :
    |jsp87Mcov L k k'| ≤ jsp87TcStd L k * jsp87TcStd L k' := by
  have hsq := jsp87Mcov_sq_le_var L k k' hL
  have hnn : 0 ≤ jsp87TcVarAt L k := by
    unfold jsp87TcVarAt
    exact jsp87Var_nonneg _ _
  have hnn' : 0 ≤ jsp87TcVarAt L k' := by
    unfold jsp87TcVarAt
    exact jsp87Var_nonneg _ _
  have hprod : (jsp87TcStd L k * jsp87TcStd L k') ^ 2
      = jsp87TcVarAt L k * jsp87TcVarAt L k' := by
    unfold jsp87TcStd
    rw [mul_pow, Real.sq_sqrt hnn, Real.sq_sqrt hnn']
  have habsq : |jsp87Mcov L k k'| ^ 2 = jsp87Mcov L k k' ^ 2 := sq_abs _
  have hnnp : 0 ≤ jsp87TcStd L k * jsp87TcStd L k' := by
    unfold jsp87TcStd
    positivity
  have h2 : |jsp87Mcov L k k'| ^ 2 ≤ (jsp87TcStd L k * jsp87TcStd L k') ^ 2 :=
    by rw [habsq, hprod]; exact hsq
  by_contra hcon
  have hlt : jsp87TcStd L k * jsp87TcStd L k' < |jsp87Mcov L k k'| := lt_of_not_ge hcon
  nlinarith [h2, hnnp]

/-- **THE COVARIANCE IS NEGATIVELY BOUNDED BY THE GEOMETRIC MEAN OF THE
MARGINAL STANDARD DEVIATIONS.**  Round 130's two transfer lemmas needed the sign
of every covariance; this is what replaces it. -/
theorem jsp87Mcov_ge_negStd (L k k' : ℕ) (hL : 1 ≤ L) :
    -(jsp87TcStd L k * jsp87TcStd L k') ≤ jsp87Mcov L k k' := by
  exact (abs_le.mp (jsp87Mcov_abs_le_std L k k' hL)).1

/-- **A DEGENERATE MARGIN FORCES A DEGENERATE COVARIANCE.** -/
theorem jsp87Mcov_eq_zero_of_var (L k k' : ℕ) (hL : 1 ≤ L)
    (hk : jsp87TcVarAt L k = 0) :
    jsp87Mcov L k k' = 0 := by
  have h := jsp87Mcov_sq_le_var L k k' hL
  rw [hk, zero_mul] at h
  nlinarith [sq_nonneg (jsp87Mcov L k k')]

/-! ## 4. THE SIGN-FREE VARIANCE SANDWICH — §5.4 OF arXiv:2512.01739 -/

/-- **THE MARGINAL VARIANCES ARE NONNEGATIVE.** -/
theorem jsp87TcVarAt_nonneg (L k : ℕ) : 0 ≤ jsp87TcVarAt L k := by
  unfold jsp87TcVarAt
  exact jsp87Var_nonneg _ _

/-- **THE STANDARD DEVIATION SQUARED IS THE VARIANCE.** -/
theorem jsp87TcStd_sq (L k : ℕ) : (jsp87TcStd L k) ^ 2 = jsp87TcVarAt L k :=
  Real.sq_sqrt (jsp87TcVarAt_nonneg L k)

/-- **THE SHIFT-ONE CORRELATION IS THE CHOWLA SUM.**  `jsp87CorrShift 1 (N+1)`
is `jsp87Chowla N`, so the shift parametrisation of §1 concerns exactly the
Chowla-type correlations of round 115. -/
theorem jsp87CorrShift_one_eq_chowla (N : ℕ) :
    jsp87CorrShift 1 (N + 1) = jsp87Chowla N := by
  have hr : Finset.range (N + 1) = insert 0 (Finset.Icc 1 N) := by
    ext k
    simp only [Finset.mem_range, Finset.mem_insert, Finset.mem_Icc]
    omega
  have hn0 : (0 : ℕ) ∉ Finset.Icc 1 N := by simp
  unfold jsp87CorrShift
  rw [hr, Finset.sum_insert hn0]
  simp [omega_zero, jsp87Chowla]

/-- **THE PRODUCT OF TWO STANDARD DEVIATIONS IS AT MOST `M`**, where `M`
dominates the marginal variances: this is the uniform scale at which the
covariances can hurt the variance of §5.4. -/
private theorem jsp87TcStd_prod_le (L H : ℕ) (M : ℝ) (hM : 0 ≤ M)
    (hσ : ∀ k ∈ Finset.range H, jsp87TcVarAt L k ≤ M)
    (k : ℕ) (hk : k ∈ Finset.range H) (k' : ℕ)
    (hk' : k' ∈ (Finset.range H).filter (fun x => k < x)) :
    jsp87TcStd L k * jsp87TcStd L k' ≤ M := by
  have h1 : jsp87TcStd L k ≤ Real.sqrt M := Real.sqrt_le_sqrt (hσ k hk)
  have h2 : jsp87TcStd L k' ≤ Real.sqrt M :=
    Real.sqrt_le_sqrt (hσ k' (Finset.mem_of_mem_filter k' hk'))
  have hnnk : 0 ≤ jsp87TcStd L k := by unfold jsp87TcStd; positivity
  have hnnk' : 0 ≤ jsp87TcStd L k' := by unfold jsp87TcStd; positivity
  calc jsp87TcStd L k * jsp87TcStd L k' ≤ jsp87TcStd L k * Real.sqrt M :=
        mul_le_mul_of_nonneg_left h2 hnnk
    _ ≤ Real.sqrt M * Real.sqrt M :=
      mul_le_mul_of_nonneg_right h1 (Real.sqrt_nonneg M)
    _ = M := by rw [← pow_two]; exact Real.sq_sqrt hM

/-- **THE SIGN-FREE LOWER BOUND — THE MIRROR OF ROUND 130'S
`jsp87TcVar_le_diag_add`, WITH NO SIGN HYPOTHESIS ON THE COVARIANCES.**

If every marginal variance of `ω` over the window is at most `M`, then

```
∑_k 4^{-(k+1)} Var (ω(N+k))  −  M   ≤   Var (N ↦ T(N,H)) .
```

**This is what closes the gap left by round 130.**  Its hypothesis there,
`0 ≤ jsp87Mcov` at every pair, is exactly the sign statement that Cauchy–Schwarz
(§3) makes unnecessary: `Cov ≥ −σσ' ≥ −M`, and the total weight of the
covariances is at most `1` (`jsp87Tw_pair_le_one`). -/
theorem jsp87TcVar_ge_diag_sub (L H : ℕ) (hL : 1 ≤ L) (M : ℝ) (hM : 0 ≤ M)
    (hσ : ∀ k ∈ Finset.range H, jsp87TcVarAt L k ≤ M) :
    (∑ k ∈ Finset.range H, (jsp87Tw k ^ 2) * jsp87TcVarAt L k) - M ≤ jsp87TcVar L H := by
  rw [jsp87TcVar_eq_diag_add_cov L H hL]
  have hweight : ∀ k ∈ Finset.range H, ∀ k' ∈ (Finset.range H).filter (fun x => k < x),
      0 ≤ 2 * jsp87Tw k * jsp87Tw k' := by
    intro k hk k' hk'
    have h1 : 0 ≤ jsp87Tw k := le_of_lt (jsp87Tw_pos k)
    have h2 : 0 ≤ jsp87Tw k' := le_of_lt (jsp87Tw_pos k')
    positivity
  have hcov : ∀ k ∈ Finset.range H, ∀ k' ∈ (Finset.range H).filter (fun x => k < x),
      -M ≤ jsp87Mcov L k k' := by
    intro k hk k' hk'
    have h1 := jsp87Mcov_ge_negStd L k k' hL
    have h2 := jsp87TcStd_prod_le L H M hM hσ k hk k' hk'
    linarith
  have hterm : ∀ k ∈ Finset.range H, ∀ k' ∈ (Finset.range H).filter (fun x => k < x),
      (2 * jsp87Tw k * jsp87Tw k') * jsp87Mcov L k k'
        ≥ -(2 * jsp87Tw k * jsp87Tw k') * M := by
    intro k hk k' hk'
    simpa [mul_neg] using
      mul_le_mul_of_nonneg_left (hcov k hk k' hk') (hweight k hk k' hk')
  have hoff : -M * (∑ k ∈ Finset.range H, ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
        2 * jsp87Tw k * jsp87Tw k')
      ≤ ∑ k ∈ Finset.range H, ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
        (2 * jsp87Tw k * jsp87Tw k') * jsp87Mcov L k k' := by
    calc -M * (∑ k ∈ Finset.range H, ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
          2 * jsp87Tw k * jsp87Tw k')
        = ∑ k ∈ Finset.range H, ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
            (-(2 * jsp87Tw k * jsp87Tw k') * M) := by
            rw [Finset.mul_sum (s := Finset.range H)
              (fun k => ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
                2 * jsp87Tw k * jsp87Tw k') (-M)]
            refine Finset.sum_congr rfl fun k _ => ?_
            rw [Finset.mul_sum (s := (Finset.range H).filter (fun x => k < x))
              (fun k' => 2 * jsp87Tw k * jsp87Tw k') (-M)]
            apply Finset.sum_congr rfl
            intro i _
            ring
      _ ≤ ∑ k ∈ Finset.range H, ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
            (2 * jsp87Tw k * jsp87Tw k') * jsp87Mcov L k k' :=
        Finset.sum_le_sum fun k hk => Finset.sum_le_sum (hterm k hk)
  have hpair := jsp87Tw_pair_le_one H
  have h1 : (∑ k ∈ Finset.range H, ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
      2 * jsp87Tw k * jsp87Tw k') * M ≤ M :=
    by simpa using mul_le_mul_of_nonneg_right hpair hM
  have h2 : -M ≤ -M * (∑ k ∈ Finset.range H,
      ∑ k' ∈ (Finset.range H).filter (fun x => k < x), 2 * jsp87Tw k * jsp87Tw k') := by
    rw [mul_comm]
    linarith
  have h3 : -M ≤ ∑ k ∈ Finset.range H,
      ∑ k' ∈ (Finset.range H).filter (fun x => k < x),
        (2 * jsp87Tw k * jsp87Tw k') * jsp87Mcov L k k' := le_trans h2 hoff
  linarith

/-- **THE COMPLETE §5.4 VARIANCE SANDWICH — THE CROWN OF THIS ROUND.**

For **any** `M ≥ 0` dominating the marginal variances of `ω` over the window
and **any** `ε ≥ 0` dominating the covariances:

```
∑_k 4^{-(k+1)} Var (ω(N+k))  −  M   ≤   Var (N ↦ T(N,H))
                                      ≤   ∑_k 4^{-(k+1)} Var (ω(N+k))  +  ε .
```

Round 130 proved the upper half **under the hypothesis `0 ≤ jsp87Mcov`**;
`jsp87TcVar_ge_diag_sub` (Cauchy–Schwarz, §3) proves the lower half **under no
hypothesis at all**, so §5.4 of arXiv:2512.01739 is reduced to the two scalar
bounds it really needs. -/
theorem jsp87TcVar_sandwich (L H : ℕ) (hL : 1 ≤ L) (M ε : ℝ) (hM : 0 ≤ M) (hε : 0 ≤ ε)
    (hσ : ∀ k ∈ Finset.range H, jsp87TcVarAt L k ≤ M)
    (hcov : ∀ k ∈ Finset.range H, ∀ k' ∈ (Finset.range H).filter (fun x => k < x),
      jsp87Mcov L k k' ≤ ε) :
    (∑ k ∈ Finset.range H, (jsp87Tw k ^ 2) * jsp87TcVarAt L k) - M ≤ jsp87TcVar L H ∧
      jsp87TcVar L H ≤ (∑ k ∈ Finset.range H, (jsp87Tw k ^ 2) * jsp87TcVarAt L k) + ε :=
  ⟨jsp87TcVar_ge_diag_sub L H hL M hM hσ, jsp87TcVar_le_diag_add L H hL ε hε hcov⟩

/-! ## 5. Machine-checked instances -/

theorem jsp87CorrShift_thousand_one : jsp87CorrShift 1 1001 = 4319 := by
  rw [jsp87CorrShift_one_eq_chowla 1000]
  exact jsp87Chowla_thousand

theorem jsp87CorrShift_hundred_one : jsp87CorrShift 1 101 = 284 := by
  rw [jsp87CorrShift_one_eq_chowla 100]
  exact jsp87Chowla_hundred

theorem jsp87Mcov_ten_zero_one :
    |jsp87Mcov 10 0 1| ≤ jsp87TcStd 10 0 * jsp87TcStd 10 1 :=
  jsp87Mcov_abs_le_std 10 0 1 (by omega)

theorem jsp87Mcov_three_zero_one_le :
    jsp87Mcov 3 0 1 ≤ jsp87TcStd 3 0 * jsp87TcStd 3 1 :=
  (abs_le.mp (jsp87Mcov_abs_le_std 3 0 1 (by omega))).2

/-- **THE ROUND IN ONE THEOREM.** -/
theorem jsp87_corrShift_summary (L k k' : ℕ) (hL : 1 ≤ L) :
    jsp87CorrAt L k (k + 1) + jsp87CorrCut k 1 = jsp87CorrShift 1 (L + k) ∧
      jsp87Mcov L k k' ^ 2 ≤ jsp87TcVarAt L k * jsp87TcVarAt L k' := by
  exact ⟨jsp87CorrAt_shiftEq k 1 L, jsp87Mcov_sq_le_var L k k' hL⟩

end JSP87
