/-
Copyright (c) 2026. Released under Apache 2.0.
Authors: JSP-000087 formalization (Yi-111-a).
-/
import JSPProblem.Primary

/-!
# JSP-000087, round 83 : the LEVEL SETS of `ω` as primary (carry-free) series

Rounds 37–82 attacked the Erdős series `S = ∑' n, ω n 2^-(n+1)` from thirty
odd directions.  Round 47 introduced the **primary (carry-free)** criterion
`jsp87Binary_irrational_iff` and applied it to *two* re-encodings of `ω`:
the parities `ω n mod 2` and the primality indicator `[n prime]`.  In both cases
it had to reach for a *different* arithmetic function.

**This round stays with `ω` itself, but decomposes it into its level sets.**  For
each `k` the level indicator

`jsp87Level k n = [ω n = k]`,   `jsp87AtLeast k n = [k ≤ ω n]`

is a `{0,1}`-valued sequence, so the series

`L k = ∑' n, jsp87Level k n · 2^-(n+1)`,   `A k = ∑' n, jsp87AtLeast k n · 2^-(n+1)`

are *primary*: they never carry, and their binary digits are **literally** the
statements "`ω N = k`" and "`k ≤ ω N`" (`jsp87LevelSeries_digit`).

## 1. New arithmetic

* `exists_omega_eq_ge` : **`ω` attains every value `k ≥ 1` on an unbounded set.**
* `omega_mul_one_add` : **the key multiplicative move.**  For `n, t > 0`,
  `ω (n · (1 + t·n)) > ω n`: a prime dividing `1 + t·n` is new, and it is
  coprime to `n`.
* `omega_eq_one_iff_primePow` : **`ω n = 1` iff `n` is a prime power**, hence
  `jsp87Level 1` is the prime-power indicator.

## 2. THE MAIN RESULT — a complete classification of two countable families

* `jsp87Level_not_eventuallyPeriodic` (k ≥ 1) and `jsp87AtLeast_not_eventuallyPeriodic`
  (k ≥ 2) : **both indicators are aperiodic**, from scratch, by freezing an
  eventual period and then contradicting it with `n ↦ n (1 + t n)`.
* `jsp87LevelSeries_irrational` : **for every `k ≥ 1`, the series
  `∑' n, [ω n = k] · 2^-(n+1)` is irrational** — a countable family of
  irrational numbers built from `ω` alone, each proved from the aperiodicity of
  its own digit string.
* `jsp87AtLeastSeries_irrational` : the same for `∑' n, [k ≤ ω n] · 2^-(n+1)`,
  `k ≥ 2`.
* **The rational members are exactly the trivial ones**, computed exactly:
  `jsp87LevelSeries 0 = 3/4`, `jsp87AtLeastSeries 0 = 1`, `jsp87AtLeastSeries 1 = 1/4`.
  Hence `jsp87LevelSeries_irrational_iff` and `jsp87AtLeastSeries_irrational_iff`
  classify the two families completely.
* `jsp87LevelSeries_ne` : the level series are **pairwise distinct**, so the two
  families are countable sets of *explicitly described* irrationals in `(0, 1)`.

## 3. Why this still does not close the gate

The two families are generated by `ω`, but their digit strings are the
*indicators* of the level sets, not `ω` itself: the Erdős series carries
(round 41's `jsp87_digit_one : jsp87Digit 1 = 1` although `ω 1 = 0`), so its
digits are not the level indicators either.  A countable sum of irrationals is
not irrational (`jsp87Series = ∑ k, k · L k` numerically, and `A k → 0`), which is
recorded here as `jsp87Series_rational_of_atLeast_periodic` rather than hoped
away: rationality of `S` forces nothing about the aperiodicity of the level
series — they are aperiodic unconditionally.  The gate therefore still waits on
the single statement `jsp87_digit_not_eventuallyPeriodic`, the aperiodicity of
the *binary digits of the carried series*, i.e. the content of the uniform
prime-`k`-tuples hypothesis in Pratt's result (arXiv:2409.15185).
-/

namespace JSP87

/-! ## 1. The level indicators -/

/-- `jsp87Level k n = 1` iff `n` has exactly `k` distinct prime factors. -/
def jsp87Level (k n : ℕ) : ℕ := if omega n = k then 1 else 0

/-- `jsp87AtLeast k n = 1` iff `n` has at least `k` distinct prime factors. -/
def jsp87AtLeast (k n : ℕ) : ℕ := if k ≤ omega n then 1 else 0

/-- **The level-`k` series** `L k = ∑' n, [ω n = k] · 2^-(n+1)`. -/
noncomputable def jsp87LevelSeries (k : ℕ) : ℝ := jsp87BinarySeries fun n => jsp87Level k n

/-- **The "at least `k`" series** `A k = ∑' n, [k ≤ ω n] · 2^-(n+1)`. -/
noncomputable def jsp87AtLeastSeries (k : ℕ) : ℝ := jsp87BinarySeries fun n => jsp87AtLeast k n

theorem jsp87Level_le (k n : ℕ) : jsp87Level k n ≤ 1 := by
  unfold jsp87Level
  split <;> omega

theorem jsp87Level_eq_one_iff (k n : ℕ) : jsp87Level k n = 1 ↔ omega n = k := by
  unfold jsp87Level
  split <;> simp_all

theorem jsp87Level_eq_zero_iff (k n : ℕ) : jsp87Level k n = 0 ↔ omega n ≠ k := by
  unfold jsp87Level
  split <;> simp_all

theorem jsp87Level_eq_one_of_omega_eq {k n : ℕ} (h : omega n = k) : jsp87Level k n = 1 :=
  (jsp87Level_eq_one_iff k n).2 h

theorem jsp87Level_eq_zero_of_omega_ne {k n : ℕ} (h : omega n ≠ k) : jsp87Level k n = 0 :=
  (jsp87Level_eq_zero_iff k n).2 h

theorem jsp87AtLeast_le (k n : ℕ) : jsp87AtLeast k n ≤ 1 := by
  unfold jsp87AtLeast
  split <;> omega

theorem jsp87AtLeast_eq_one_iff (k n : ℕ) : jsp87AtLeast k n = 1 ↔ k ≤ omega n := by
  unfold jsp87AtLeast
  split <;> simp_all

theorem jsp87AtLeast_eq_zero_iff (k n : ℕ) : jsp87AtLeast k n = 0 ↔ omega n < k := by
  unfold jsp87AtLeast
  split <;> simp_all

theorem jsp87Level_zero_iff_le_one (n : ℕ) : jsp87Level 0 n = 1 ↔ n ≤ 1 :=
  (jsp87Level_eq_one_iff 0 n).trans omega_eq_zero_iff

/-- The level indicators partition: `1 = [k = 0] + ∑_{k ≥ 1} [k ≤ ω n]` is
recorded in §6 below; here the *pointwise* difference identity that links the two
families. -/
theorem jsp87AtLeast_sub_level (k n : ℕ) :
    jsp87AtLeast k n - jsp87AtLeast (k + 1) n = jsp87Level k n := by
  rcases Nat.lt_trichotomy (omega n) k with h | h | h
  · have h1 : jsp87AtLeast k n = 0 := (jsp87AtLeast_eq_zero_iff k n).2 h
    have h2 : jsp87AtLeast (k + 1) n = 0 := by
      refine (jsp87AtLeast_eq_zero_iff _ n).2 ?_
      omega
    have h3 : jsp87Level k n = 0 := jsp87Level_eq_zero_of_omega_ne (by omega)
    omega
  · have h1 : jsp87AtLeast k n = 1 := (jsp87AtLeast_eq_one_iff k n).2 (Nat.le_of_eq h.symm)
    have h2 : jsp87AtLeast (k + 1) n = 0 := by
      refine (jsp87AtLeast_eq_zero_iff _ n).2 ?_
      omega
    have h3 : jsp87Level k n = 1 := jsp87Level_eq_one_of_omega_eq h
    omega
  · have h1 : jsp87AtLeast k n = 1 := (jsp87AtLeast_eq_one_iff k n).2 (by omega)
    have h2 : jsp87AtLeast (k + 1) n = 1 := (jsp87AtLeast_eq_one_iff _ n).2 (by omega)
    have h3 : jsp87Level k n = 0 := jsp87Level_eq_zero_of_omega_ne (by omega)
    omega

/-! ## 2. New arithmetic: `ω` attains every value, and `ω (n(1 + t n)) > ω n` -/

theorem omega_pos_of_ge_two {m : ℕ} (hm : 2 ≤ m) : 0 < omega m := by
  obtain ⟨p, hp, hpd⟩ := Nat.ne_one_iff_exists_prime_dvd.mp (by omega : (m : ℕ) ≠ 1)
  exact omega_pos_of_prime_dvd hp hpd (by omega)

/-- `q ∣ q ^ k` for `1 ≤ k` — the arithmetic of a prime ray. -/
theorem dvd_self_pow {q k : ℕ} (hk : 1 ≤ k) : q ∣ q ^ k := by
  obtain ⟨k', rfl⟩ : ∃ k', k = k' + 1 := ⟨k - 1, by omega⟩
  rw [pow_succ]
  exact Nat.dvd_mul_left q (q ^ k')

/-- **`ω` attains every value `k ≥ 1` on an unbounded set.**  The base case is the
ray `2^j`; the induction step multiplies by a fresh large prime. -/
theorem exists_omega_eq_ge : ∀ k : ℕ, 1 ≤ k → ∀ N : ℕ, ∃ n, N ≤ n ∧ omega n = k := by
  intro k
  induction k with
  | zero =>
      intro h
      omega
  | succ k ih =>
      intro _ N
      by_cases hm : k = 0
      · obtain ⟨j, hj, h2j⟩ := exists_pow_two_ge N
        refine ⟨2 ^ j, h2j, ?_⟩
        have hk0 : k + 1 = 1 := by omega
        rw [hk0]
        exact omega_prime_pow (p := 2) (k := j) (by norm_num : Nat.Prime 2) hj
      · have hk1 : 1 ≤ k := by omega
        obtain ⟨n, hn, hω⟩ := ih hk1 N
        have hnpos : 0 < n := by
          rcases Nat.eq_zero_or_pos n with h | h
          · have h1 := hω
            simp only [h, omega_zero] at h1
            omega
          · exact h
        obtain ⟨q, hq, hqp⟩ := Nat.exists_infinite_primes (max N (n + 1))
        have hqnd : q ∉ n.primeFactors := by
          intro hmem
          obtain ⟨hqp', hqn, _⟩ := Nat.mem_primeFactors.mp hmem
          exact absurd (Nat.le_of_dvd hnpos hqn) (by omega)
        refine ⟨n * q, ?_, ?_⟩
        · exact le_trans (le_max_left N (n + 1) |>.trans hq) (Nat.le_mul_of_pos_left q hnpos)
        · rw [omega_mul_of_not_dvd hnpos hqp hqnd]
          omega

/-- **THE KEY MULTIPLICATIVE MOVE.**  For `n, t > 0`,
`ω (n · (1 + t·n)) > ω n`: any prime dividing `1 + t·n` is coprime to `n`, hence
new, and `n · q` divides `n · (1 + t·n)`. -/
theorem omega_mul_one_add (n t : ℕ) (hn : 0 < n) (ht : 0 < t) :
    omega n < omega (n * (1 + t * n)) := by
  have htn : 1 ≤ t * n := by
    have := Nat.mul_pos ht hn
    omega
  obtain ⟨q, hq, hqd⟩ := Nat.ne_one_iff_exists_prime_dvd.mp (by omega : (1 + t * n : ℕ) ≠ 1)
  have hqn : ¬ q ∣ n := by
    intro h
    have htn' : q ∣ t * n := by simpa [Nat.mul_comm] using dvd_mul_of_dvd_left h t
    have hone : q ∣ 1 := (Nat.dvd_add_right htn').mp (by rw [Nat.add_comm]; exact hqd)
    have hq2 : 2 ≤ q := hq.two_le
    exact absurd (Nat.le_of_dvd (by norm_num : (0 : ℕ) < 1) hone) (by omega)
  have hdiv : n * q ∣ n * (1 + t * n) := by
    simpa [Nat.mul_comm] using Nat.mul_dvd_mul_right hqd n
  have hmono : omega (n * q) ≤ omega (n * (1 + t * n)) := omega_mono hdiv (by positivity)
  have hqnd : q ∉ n.primeFactors := by
    intro hmem
    obtain ⟨hqp', hqn', _⟩ := Nat.mem_primeFactors.mp hmem
    exact hqn hqn'
  rw [omega_mul_of_not_dvd hn hq hqnd] at hmono
  omega

/-- **`ω n = 1` iff `n` is a prime power.**  Mathlib has no such statement; it is
the arithmetic content of the level-`1` series. -/
theorem omega_eq_one_iff_primePow (n : ℕ) :
    omega n = 1 ↔ ∃ p m : ℕ, p.Prime ∧ 1 ≤ m ∧ n = p ^ m := by
  constructor
  · intro h
    have key : ∀ m : ℕ, omega m = 1 -> ∃ p k : ℕ, p.Prime ∧ 1 ≤ k ∧ m = p ^ k := by
      intro m
      induction m using Nat.strong_induction_on with
      | _ m ih =>
          intro hm1
          have hm2 : 2 ≤ m := by
            by_contra hc
            have hle : m ≤ 1 := by omega
            have h0 : omega m = 0 := omega_eq_zero_iff.mpr hle
            exact absurd (hm1.symm.trans h0) (by omega)
          have hmpos : 0 < m := by omega
          obtain ⟨p, hset⟩ := Finset.card_eq_one.mp (by simpa only [omega] using hm1)
          have hmemP : p ∈ m.primeFactors := by
            rw [hset]
            exact Finset.mem_singleton_self p
          obtain ⟨hp, hpd, _⟩ := Nat.mem_primeFactors.mp hmemP
          have hmul : p * (m / p) = m := Nat.mul_div_cancel' hpd
          have hmdivp : m / p ∣ m :=
            ⟨p, hmul.symm.trans (Nat.mul_comm _ _).symm⟩
          have hpos : 0 < m / p := by
            rcases Nat.eq_zero_or_pos (m / p) with h | h
            · have hmz : m = 0 := by rw [← hmul, h, Nat.mul_zero]
              exact absurd hmz (by omega)
            · exact h
          by_cases h1 : m / p = 1
          · have hmp : m = p := by
              rw [← hmul, h1, Nat.mul_one]
            have hmp' : m = p ^ 1 := by rw [hmp, pow_one]
            exact ⟨p, 1, hp, by norm_num, hmp'⟩
          · have h2 : 2 ≤ m / p := by omega
            have hsub : (m / p).primeFactors ⊆ {p} := by
              intro b hb
              obtain ⟨hbp, hbd, _⟩ := Nat.mem_primeFactors.mp hb
              have hbm : b ∈ m.primeFactors :=
                Nat.mem_primeFactors.mpr ⟨hbp, hbd.trans hmdivp, hmpos.ne'⟩
              rw [hset] at hbm
              simpa using hbm
            have hcard1 : (m / p).primeFactors.card = 1 := by
              have hle : (m / p).primeFactors.card ≤ 1 := by
                simpa using Finset.card_le_card hsub
              obtain ⟨r, hr, hrd⟩ := Nat.ne_one_iff_exists_prime_dvd.mp h1
              have hmemR : r ∈ (m / p).primeFactors :=
                Nat.Prime.mem_primeFactors hr hrd (by omega)
              have hge : 0 < (m / p).primeFactors.card := Finset.card_pos.mpr ⟨r, hmemR⟩
              omega
            have hlt : m / p < m := by
              have hle' : m / p ≤ m := Nat.div_le_self m p
              have hne : m / p ≠ m := by
                intro hc
                have h1' : p * m = m := by
                  calc p * m = p * (m / p) := by rw [hc]
                    _ = m := hmul
                have hp1 : p = 1 := Nat.mul_left_cancel hmpos
                  (calc m * p = p * m := Nat.mul_comm _ _
                    _ = m * 1 := by rw [h1', Nat.mul_one])
                have hp2 : 2 ≤ p := hp.two_le
                omega
              exact lt_of_le_of_ne hle' hne
            obtain ⟨q, k, hq, hk, hkey2⟩ := ih (m / p) hlt hcard1
            have hqd : q ∣ q ^ k := dvd_self_pow hk
            have hqmem : q ∈ (m / p).primeFactors := by
              rw [hkey2]
              exact Nat.Prime.mem_primeFactors hq hqd (by omega)
            have hqp : q = p := by
              have : q ∈ {p} := hsub hqmem
              simpa using this
            refine ⟨q, k + 1, hq, by omega, ?_⟩
            have hm_eq : m = p * (m / p) := hmul.symm
            have hres : m = q ^ (k + 1) := by
              rw [hm_eq, hkey2, hqp, pow_succ, Nat.mul_comm]
            exact hres
    obtain ⟨p, k, hp, hk, hkey⟩ := key n h
    exact ⟨p, k, hp, hk, hkey⟩
  · rintro ⟨p, m, hp, hm, rfl⟩
    exact omega_prime_pow hp hm

/-- **`ω n = 1` iff `n` is a prime power**: the level-`1` series is the
prime-power series. -/
theorem jsp87Level_one_eq_primePow (n : ℕ) : jsp87Level 1 n = 1 ↔ ∃ p m, p.Prime ∧ 1 ≤ m ∧ n = p ^ m :=
  (jsp87Level_eq_one_iff 1 n).trans (omega_eq_one_iff_primePow n)

/-! ## 3. Aperiodicity of the level indicators -/

/-- An eventual period freezes the level indicator along the progression
`m + t j`, for every `m ≥ N`. -/
theorem jsp87Level_frozen {k t N m : ℕ} (_ht : 0 < t)
    (hper : ∀ n, N ≤ n → jsp87Level k (n + t) = jsp87Level k n) (hm : N ≤ m) (j : ℕ) :
    jsp87Level k (m + t * j) = jsp87Level k m := by
  induction j with
  | zero => simp
  | succ j ih =>
      have hstep : m + t * Nat.succ j = (m + t * j) + t := by
        rw [Nat.succ_eq_add_one, Nat.mul_succ, Nat.add_assoc]
      rw [hstep, hper _ (by omega)]
      exact ih

/-- An eventual period freezes the "at least" indicator along the progression
`m + t j`, for every `m ≥ N`. -/
theorem jsp87AtLeast_frozen {k t N m : ℕ} (_ht : 0 < t)
    (hper : ∀ n, N ≤ n → jsp87AtLeast k (n + t) = jsp87AtLeast k n) (hm : N ≤ m) (j : ℕ) :
    jsp87AtLeast k (m + t * j) = jsp87AtLeast k m := by
  induction j with
  | zero => simp
  | succ j ih =>
      have hstep : m + t * Nat.succ j = (m + t * j) + t := by
        rw [Nat.succ_eq_add_one, Nat.mul_succ, Nat.add_assoc]
      rw [hstep, hper _ (by omega)]
      exact ih

/-- **THE LEVEL INDICATORS ARE APERIODIC** (`k ≥ 1`).  Suppose `t` were an
eventual period from `N`.  Take `m ≥ N` with `ω m = k`; the level indicator is
`1` on the whole progression `m + t j`, hence at
`m + t (m·m) = m (1 + t m)`, but there `ω` is strictly larger than `k`
(`omega_mul_one_add`). -/
theorem jsp87Level_not_eventuallyPeriodic (k : ℕ) (hk : 1 ≤ k) :
    ¬ ∃ t N : ℕ, 0 < t ∧ 1 ≤ N ∧ ∀ n, N ≤ n → jsp87Level k (n + t) = jsp87Level k n := by
  rintro ⟨t, N, ht, _, hper⟩
  obtain ⟨m, hm, hω⟩ := exists_omega_eq_ge k hk N
  have hfreeze : ∀ j, jsp87Level k (m + t * j) = 1 :=
    fun j => (jsp87Level_frozen ht hper hm j).trans (jsp87Level_eq_one_of_omega_eq hω)
  have hbig := hfreeze (m * m)
  have heq : m + t * (m * m) = m * (1 + t * m) := by ring
  rw [heq] at hbig
  have hlt : omega m < omega (m * (1 + t * m)) := omega_mul_one_add m t (by omega) (by omega)
  have hzero : jsp87Level k (m * (1 + t * m)) = 0 := jsp87Level_eq_zero_of_omega_ne (by omega)
  exact absurd hzero (by omega : ¬ (jsp87Level k (m * (1 + t * m)) = 0))

/-- **THE "AT LEAST" INDICATORS ARE APERIODIC** (`k ≥ 2`).  Same mechanism, read in
the other direction: start from `ω m = k - 1`, where the indicator is `0`, and use
`m (1 + t m)`, where `ω ≥ k`. -/
theorem jsp87AtLeast_not_eventuallyPeriodic (k : ℕ) (hk : 2 ≤ k) :
    ¬ ∃ t N : ℕ, 0 < t ∧ 1 ≤ N ∧ ∀ n, N ≤ n → jsp87AtLeast k (n + t) = jsp87AtLeast k n := by
  rintro ⟨t, N, ht, _, hper⟩
  have hk1 : 1 ≤ k - 1 := by omega
  obtain ⟨m, hm, hω⟩ := exists_omega_eq_ge (k - 1) hk1 N
  have hzero : jsp87AtLeast k m = 0 := (jsp87AtLeast_eq_zero_iff k m).2 (by omega)
  have hfreeze : ∀ j, jsp87AtLeast k (m + t * j) = 0 :=
    fun j => (jsp87AtLeast_frozen ht hper hm j).trans hzero
  have hbig := hfreeze (m * m)
  have heq : m + t * (m * m) = m * (1 + t * m) := by ring
  rw [heq] at hbig
  have hlt : omega m < omega (m * (1 + t * m)) := omega_mul_one_add m t (by omega) (by omega)
  have hone : jsp87AtLeast k (m * (1 + t * m)) = 1 := (jsp87AtLeast_eq_one_iff k _).2 (by omega)
  exact absurd hbig (by omega : ¬ (jsp87AtLeast k (m * (1 + t * m)) = 0))

/-! ## 4. The level series: no carrying, and their digits -/

theorem summable_jsp87Level (k : ℕ) : Summable (jsp87BitTerm fun n => jsp87Level k n) :=
  summable_jsp87BitTerm _ fun n => jsp87Level_le k n

theorem summable_jsp87AtLeast (k : ℕ) : Summable (jsp87BitTerm fun n => jsp87AtLeast k n) :=
  summable_jsp87BitTerm _ fun n => jsp87AtLeast_le k n

/-- The level tail never reaches `1`: past every cut point there is a number whose
`ω`-value is not `k`.  This is exactly the "no carrying" hypothesis of
`jsp87Binary_irrational_iff`. -/
theorem jsp87LevelTail_lt_one (k N : ℕ) : jsp87BinaryTail (fun n => jsp87Level k n) N < 1 := by
  obtain ⟨n, hn, hω⟩ := exists_omega_eq_ge (k + 1) (by omega) N
  exact jsp87BinaryTail_lt_one _ (fun n => jsp87Level_le k n) N
    ⟨n - N, by rw [Nat.add_sub_of_le hn]; exact jsp87Level_eq_zero_of_omega_ne (by omega)⟩

/-- The same for the "at least" indicators (`k ≥ 2`). -/
theorem jsp87AtLeastTail_lt_one (k N : ℕ) (hk : 2 ≤ k) :
    jsp87BinaryTail (fun n => jsp87AtLeast k n) N < 1 := by
  obtain ⟨n, hn, hω⟩ := exists_omega_eq_ge (k - 1) (by omega) N
  exact jsp87BinaryTail_lt_one _ (fun n => jsp87AtLeast_le k n) N
    ⟨n - N, by rw [Nat.add_sub_of_le hn]; exact (jsp87AtLeast_eq_zero_iff k _).2 (by omega)⟩

theorem jsp87LevelSeries_nonneg (k : ℕ) : 0 ≤ jsp87LevelSeries k :=
  tsum_nonneg fun n => jsp87BitTerm_nonneg _ n

theorem jsp87AtLeastSeries_nonneg (k : ℕ) : 0 ≤ jsp87AtLeastSeries k :=
  tsum_nonneg fun n => jsp87BitTerm_nonneg _ n

/-- **THE LEVEL SERIES IS STRICTLY POSITIVE** (`k ≥ 1`): some digit is `1`, and the
rescaled tail is positive. -/
theorem jsp87LevelSeries_pos (k : ℕ) (hk : 1 ≤ k) : 0 < jsp87LevelSeries k := by
  obtain ⟨n, _, hω⟩ := exists_omega_eq_ge k (by omega) 2
  have hsplit := jsp87Binary_split (fun m => jsp87Level k m) (fun m => jsp87Level_le k m) 1
    (by norm_num)
  have htail : 0 < jsp87BinaryTail (fun m => jsp87Level k m) 1 :=
    jsp87BinaryTail_pos _ (fun m => jsp87Level_le k m) 1
      ⟨n - 1, by
        rw [Nat.add_sub_of_le (by omega)]
        have h1 := jsp87Level_eq_one_of_omega_eq hω
        omega⟩
  have hpre : (0 : ℝ) ≤ jsp87BinaryInt (fun m => jsp87Level k m) 1 := Nat.cast_nonneg _
  show 0 < jsp87BinarySeries (fun m => jsp87Level k m)
  linarith

/-- **THE LEVEL SERIES IS BELOW `1`.**  A primary series with a zero digit never
carries: at the cut point `n` the prefix is at most `2^n - 1` and the tail is
strictly below `1`. -/
theorem jsp87LevelSeries_lt_one (k : ℕ) (hk : 1 ≤ k) : jsp87LevelSeries k < 1 := by
  obtain ⟨n, _, hω⟩ := exists_omega_eq_ge (k + 1) (by omega) 1
  have hsplit := jsp87Binary_split (fun m => jsp87Level k m) (fun m => jsp87Level_le k m) n
    (by omega)
  have hpre := jsp87BinaryInt_bounds _ (fun m => jsp87Level_le k m) n
  have htail := jsp87LevelTail_lt_one k n
  have htwo : 0 < (2 : ℝ) ^ n := by positivity
  have hle : ((jsp87BinaryInt (fun m => jsp87Level k m) n : ℕ) : ℝ) ≤ (2 : ℝ) ^ n - 1 := by
    have hkey : ((2 : ℕ) ^ n - 1 : ℕ) = ((2 : ℝ) ^ n - 1 : ℝ) := by
      rw [Nat.cast_sub (one_le_two_pow n)]
      norm_num
    have hge : ((jsp87BinaryInt (fun m => jsp87Level k m) n : ℕ) : ℝ)
        ≤ ((2 : ℕ) ^ n - 1 : ℕ) := by exact_mod_cast hpre
    rw [hkey] at hge
    exact hge
  have hres : jsp87BinarySeries (fun m => jsp87Level k m) < 1 := by
    by_contra hcon
    push Not at hcon
    have h1 : (2 : ℝ) ^ n * 1 ≤ (2 : ℝ) ^ n * jsp87BinarySeries (fun m => jsp87Level k m) :=
      mul_le_mul_of_nonneg_left hcon (le_of_lt htwo)
    linarith
  exact hres

/-- **THE DIGIT OF THE LEVEL SERIES IS THE LEVEL INDICATOR.**  At place `N` the
binary digit of `L k` is the statement "`N` has exactly `k` distinct prime
factors"; nothing ever carries. -/
theorem jsp87LevelSeries_digit (k N : ℕ) (hN : 1 ≤ N) :
    ((jsp87Level k N : ℕ) : ℤ)
      = ⌊2 ^ (N + 1) * jsp87LevelSeries k⌋ - 2 * ⌊2 ^ N * jsp87LevelSeries k⌋ :=
  jsp87Binary_digit _ (fun m => jsp87Level_le k m) (fun m => jsp87LevelTail_lt_one k m) N hN

/-- The same for the "at least" series. -/
theorem jsp87AtLeastSeries_digit (k N : ℕ) (hk : 2 ≤ k) (hN : 1 ≤ N) :
    ((jsp87AtLeast k N : ℕ) : ℤ)
      = ⌊2 ^ (N + 1) * jsp87AtLeastSeries k⌋ - 2 * ⌊2 ^ N * jsp87AtLeastSeries k⌋ :=
  jsp87Binary_digit _ (fun m => jsp87AtLeast_le k m)
    (fun m => jsp87AtLeastTail_lt_one k m hk) N hN

/-- **THE PREFIX OF THE LEVEL SERIES IS A GENUINE `N`-BIT INTEGER.** -/
theorem jsp87LevelPrefix_bounds (k N : ℕ) :
    jsp87BinaryInt (fun n => jsp87Level k n) N ≤ 2 ^ N - 1 :=
  jsp87BinaryInt_bounds _ (fun n => jsp87Level_le k n) N

/-- **AND THE BINARY FLOOR IS THE PREFIX** (no carrying, `k ≥ 1`). -/
theorem jsp87LevelSeries_floor (k N : ℕ) (_hk : 1 ≤ k) (hN : 1 ≤ N) :
    ((⌊2 ^ N * jsp87LevelSeries k⌋ : ℤ) : ℝ)
      = ((jsp87BinaryInt (fun n => jsp87Level k n) N : ℕ) : ℝ) := by
  exact_mod_cast
    (jsp87Binary_floor _ (fun n => jsp87Level_le k n) (fun n => jsp87LevelTail_lt_one k n) N hN)

/-! ## 5. THE MAIN THEOREM — a complete classification of two countable families -/

/-- **THE LEVEL-`k` SERIES IS IRRATIONAL for every `k ≥ 1`.**  A countable family of
irrational numbers built from `ω` alone: each one is a primary series whose digit
string is the level indicator, and that string is aperiodic
(`jsp87Level_not_eventuallyPeriodic`). -/
theorem jsp87LevelSeries_irrational (k : ℕ) (hk : 1 ≤ k) : Irrational (jsp87LevelSeries k) :=
  (jsp87Binary_irrational_iff (fun n => jsp87Level k n) (fun n => jsp87Level_le k n)
    (fun N => jsp87LevelTail_lt_one k N)).2 (jsp87Level_not_eventuallyPeriodic k hk)

/-- **THE "AT LEAST `k`" SERIES IS IRRATIONAL for every `k ≥ 2`.** -/
theorem jsp87AtLeastSeries_irrational (k : ℕ) (hk : 2 ≤ k) : Irrational (jsp87AtLeastSeries k) :=
  (jsp87Binary_irrational_iff (fun n => jsp87AtLeast k n) (fun n => jsp87AtLeast_le k n)
    (fun N => jsp87AtLeastTail_lt_one k N hk)).2 (jsp87AtLeast_not_eventuallyPeriodic k hk)

/-- **THE COUNTABLE FAMILIES.**  For every `k ≥ 1`, `L k` is an irrational number
strictly inside `(0, 1)`. -/
theorem jsp87LevelSeries_mem (k : ℕ) (hk : 1 ≤ k) : 0 < jsp87LevelSeries k ∧ jsp87LevelSeries k < 1 :=
  ⟨jsp87LevelSeries_pos k hk, jsp87LevelSeries_lt_one k hk⟩

/-- **THE RATIONAL MEMBERS OF THE LEVEL FAMILY, COMPUTED EXACTLY.**  `L 0 = 3/4`:
its digit string is `[n ≤ 1]`, hence eventually `0`. -/
theorem jsp87LevelSeries_zero : jsp87LevelSeries 0 = 3 / 4 := by
  have hf : ∀ n, jsp87Level 0 n ≤ 1 := fun n => jsp87Level_le 0 n
  have hper : ∀ n, 2 ≤ n → jsp87Level 0 (n + 1) = jsp87Level 0 n := by
    intro n _
    have h1 : jsp87Level 0 (n + 1) = 0 := jsp87Level_eq_zero_of_omega_ne (by
      intro hc
      have := (omega_eq_zero_iff).mp hc
      omega)
    have h2 : jsp87Level 0 n = 0 := jsp87Level_eq_zero_of_omega_ne (by
      intro hc
      have := (omega_eq_zero_iff).mp hc
      omega)
    rw [h1, h2]
  have hkey := jsp87Binary_series_eq_block _ hf (N := 2) (t := 1) (by norm_num) hper (by norm_num)
  have h0 : jsp87Level 0 0 = 1 := by simp [jsp87Level]
  have h1 : jsp87Level 0 1 = 1 := by simp [jsp87Level]
  have h2 : jsp87Level 0 2 = 0 := jsp87Level_eq_zero_of_omega_ne (by
    intro hc
    have := (omega_eq_zero_iff).mp hc
    omega)
  have hInt : (jsp87BinaryInt (fun m => jsp87Level 0 m) 2 : ℝ) = 3 := by
    rw [jsp87BinaryInt_cast]
    norm_num [jsp87BinaryInt, Finset.sum_range_succ, h0, h1]
  have hBlk : jsp87BinaryBlock (fun m => jsp87Level 0 m) 2 1 = 0 := by
    rw [jsp87BinaryBlock, Finset.sum_range_succ]
    norm_num [h2]
  rw [hInt, hBlk] at hkey
  norm_num at hkey
  show jsp87BinarySeries (fun m => jsp87Level 0 m) = 3 / 4
  linarith

/-- `A 0 = 1`: the constant digit string `[k ≤ ω n]` with `k = 0`. -/
theorem jsp87AtLeastSeries_zero : jsp87AtLeastSeries 0 = 1 := by
  have hf : ∀ n, jsp87AtLeast 0 n ≤ 1 := fun n => jsp87AtLeast_le 0 n
  have hper : ∀ n, 1 ≤ n → jsp87AtLeast 0 (n + 1) = jsp87AtLeast 0 n := by
    intro n _
    rw [(jsp87AtLeast_eq_one_iff 0 _).2 (Nat.zero_le _),
      (jsp87AtLeast_eq_one_iff 0 _).2 (Nat.zero_le _)]
  have hkey := jsp87Binary_series_eq_block _ hf (N := 1) (t := 1) (by norm_num) hper (by norm_num)
  have h0 : jsp87AtLeast 0 0 = 1 := by simp [jsp87AtLeast]
  have hInt : (jsp87BinaryInt (fun m => jsp87AtLeast 0 m) 1 : ℝ) = 1 := by
    rw [jsp87BinaryInt_cast]
    norm_num [jsp87BinaryInt, Finset.sum_range_succ, h0]
  have hBlk : jsp87BinaryBlock (fun m => jsp87AtLeast 0 m) 1 1 = 1 := by
    rw [jsp87BinaryBlock, Finset.sum_range_succ]
    norm_num [jsp87AtLeast, Nat.zero_le]
  rw [hInt, hBlk] at hkey
  norm_num at hkey
  show jsp87BinarySeries (fun m => jsp87AtLeast 0 m) = 1
  linarith

/-- `A 1 = 1/4`: the digit string is `[2 ≤ n]`. -/
theorem jsp87AtLeastSeries_one : jsp87AtLeastSeries 1 = 1 / 4 := by
  have hf : ∀ n, jsp87AtLeast 1 n ≤ 1 := fun n => jsp87AtLeast_le 1 n
  have hper : ∀ n, 2 ≤ n → jsp87AtLeast 1 (n + 1) = jsp87AtLeast 1 n := by
    intro n _
    have h1 : 1 ≤ omega (n + 1) := omega_ge_one_of_ge_two (by omega)
    have h2 : 1 ≤ omega n := omega_ge_one_of_ge_two (by omega)
    rw [(jsp87AtLeast_eq_one_iff 1 _).2 h1, (jsp87AtLeast_eq_one_iff 1 _).2 h2]
  have hkey := jsp87Binary_series_eq_block _ hf (N := 2) (t := 1) (by norm_num) hper (by norm_num)
  have h0 : jsp87AtLeast 1 0 = 0 := (jsp87AtLeast_eq_zero_iff 1 0).2 (by simp)
  have h1 : jsp87AtLeast 1 1 = 0 := (jsp87AtLeast_eq_zero_iff 1 1).2 (by simp)
  have h2 : jsp87AtLeast 1 2 = 1 := (jsp87AtLeast_eq_one_iff 1 2).2 (by native_decide : 1 ≤ omega 2)
  have hInt : (jsp87BinaryInt (fun m => jsp87AtLeast 1 m) 2 : ℝ) = 0 := by
    rw [jsp87BinaryInt_cast]
    norm_num [jsp87BinaryInt, Finset.sum_range_succ, h0, h1]
  have hBlk : jsp87BinaryBlock (fun m => jsp87AtLeast 1 m) 2 1 = 1 := by
    rw [jsp87BinaryBlock, Finset.sum_range_succ]
    norm_num [h2]
  rw [hInt, hBlk] at hkey
  norm_num at hkey
  show jsp87BinarySeries (fun m => jsp87AtLeast 1 m) = 1 / 4
  linarith

/-- **THE CLASSIFICATION OF THE LEVEL FAMILY**: rational exactly at `k = 0`. -/
theorem jsp87LevelSeries_irrational_iff (k : ℕ) : Irrational (jsp87LevelSeries k) ↔ 1 ≤ k := by
  constructor
  · intro hI
    by_cases hc : k = 0
    · rw [hc, jsp87LevelSeries_zero] at hI
      exact absurd (hI ⟨(3 : ℚ) / 4, by norm_num⟩) (by norm_num)
    · omega
  · intro hk
    exact jsp87LevelSeries_irrational k hk

/-- **THE CLASSIFICATION OF THE "AT LEAST" FAMILY**: rational exactly at `k ≤ 1`. -/
theorem jsp87AtLeastSeries_irrational_iff (k : ℕ) : Irrational (jsp87AtLeastSeries k) ↔ 2 ≤ k := by
  constructor
  · intro hI
    by_cases hc : k = 0
    · rw [hc, jsp87AtLeastSeries_zero] at hI
      exact absurd (hI ⟨(1 : ℚ), by norm_num⟩) (by norm_num)
    · by_cases hc' : k = 1
      · rw [hc', jsp87AtLeastSeries_one] at hI
        exact absurd (hI ⟨(1 : ℚ) / 4, by norm_num⟩) (by norm_num)
      · omega
  · intro hk
    exact jsp87AtLeastSeries_irrational k hk

/-- **THE LEVEL SERIES ARE PAIRWISE DISTINCT.**  Their digit strings differ, and a
primary series is determined by its digits — so `{L k : k ≥ 1}` is a countable set
of *distinct* irrationals. -/
theorem jsp87LevelSeries_ne {k k' : ℕ} (hkk' : k ≠ k') :
    jsp87LevelSeries k ≠ jsp87LevelSeries k' := by
  intro heq
  have hdigits : ∀ N, 1 ≤ N → jsp87Level k N = jsp87Level k' N := by
    intro N hN
    have h1 := jsp87LevelSeries_digit k N hN
    have h2 := jsp87LevelSeries_digit k' N hN
    rw [heq] at h1
    have h1' : (jsp87Level k N : ℤ) = (jsp87Level k' N : ℤ) := h1.trans h2.symm
    exact_mod_cast h1'
  by_cases hc : k = 0
  · have h1 := hdigits 1 (by norm_num)
    rw [hc] at h1
    have h2 : jsp87Level k' 1 = 1 := by
      rw [← h1]
      exact jsp87Level_eq_one_of_omega_eq omega_one
    have h3 : omega 1 = k' := (jsp87Level_eq_one_iff k' 1).mp h2
    have h4 : k' = 0 := by simpa using h3.symm
    exact hkk' (by rw [hc, h4])
  · obtain ⟨n, hn, hω⟩ := exists_omega_eq_ge k (by omega) 1
    have h1 := hdigits n hn
    have hone := jsp87Level_eq_one_of_omega_eq hω
    rw [hone] at h1
    exact hkk' (hω.symm.trans ((jsp87Level_eq_one_iff _ n).mp h1.symm))

/-- The two families are related by the pointwise identity of §1:
`L k = A k − A (k+1)`. -/
theorem jsp87LevelSeries_sub (k : ℕ) :
    jsp87LevelSeries k = jsp87AtLeastSeries k - jsp87AtLeastSeries (k + 1) := by
  have h1 := summable_jsp87AtLeast k
  have h2 := summable_jsp87AtLeast (k + 1)
  have hsub := Summable.tsum_sub h1 h2
  have hcongr : ∀ n : ℕ,
      jsp87BitTerm (fun m => jsp87AtLeast k m) n - jsp87BitTerm (fun m => jsp87AtLeast (k + 1) m) n
        = jsp87BitTerm (fun m => jsp87Level k m) n := by
    intro n
    have hid : jsp87AtLeast k n - jsp87AtLeast (k + 1) n = jsp87Level k n :=
      jsp87AtLeast_sub_level k n
    show ((jsp87AtLeast k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹
        - ((jsp87AtLeast (k + 1) n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹
        = ((jsp87Level k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹
    have hcast : ((jsp87AtLeast k n : ℕ) : ℝ) - ((jsp87AtLeast (k + 1) n : ℕ) : ℝ)
        = ((jsp87Level k n : ℕ) : ℝ) := by
      have hle : jsp87AtLeast k n ≤ 1 := jsp87AtLeast_le k n
      have hge : jsp87AtLeast (k + 1) n ≤ jsp87AtLeast k n := by
        by_cases hc : k + 1 ≤ omega n
        · have h1 := (jsp87AtLeast_eq_one_iff (k + 1) n).2 hc
          have h2 := (jsp87AtLeast_eq_one_iff k n).2 (Nat.le_of_lt (Nat.succ_le_iff.mp hc))
          rw [h1, h2]
        · have hlt' : omega n < k + 1 := by omega
          have h1 := (jsp87AtLeast_eq_zero_iff (k + 1) n).2 hlt'
          rw [h1]
          exact_mod_cast Nat.zero_le (jsp87AtLeast k n)
      rw [← hid]
      exact (Nat.cast_sub (m := jsp87AtLeast (k + 1) n) (n := jsp87AtLeast k n) hge).symm
    calc ((jsp87AtLeast k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹
            - ((jsp87AtLeast (k + 1) n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹
        = (((jsp87AtLeast k n : ℕ) : ℝ) - ((jsp87AtLeast (k + 1) n : ℕ) : ℝ))
            * ((2 : ℝ) ^ (n + 1))⁻¹ := by ring
      _ = ((jsp87Level k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹ := by rw [hcast]
  show jsp87BinarySeries (fun n => jsp87Level k n)
    = jsp87BinarySeries (fun n => jsp87AtLeast k n)
      - jsp87BinarySeries (fun n => jsp87AtLeast (k + 1) n)
  unfold jsp87BinarySeries
  calc (∑' n : ℕ, jsp87BitTerm (fun m => jsp87Level k m) n)
      = ∑' n : ℕ, (jsp87BitTerm (fun m => jsp87AtLeast k m) n
          - jsp87BitTerm (fun m => jsp87AtLeast (k + 1) m) n) := tsum_congr fun n => (hcongr n).symm
    _ = _ := hsub

/-- **THE LEVEL-1 SERIES IS STRICTLY ABOVE `1/8`.**  Its digit string is the
prime-power indicator (`jsp87Level_one_eq_primePow`), so the places `2` and `4`
contribute `1/8 + 1/32`. -/
theorem jsp87LevelSeries_one_gt : 1 / 8 < jsp87LevelSeries 1 := by
  have hnonneg : ∀ i : ℕ, 0 ≤ ((jsp87Level 1 i : ℕ) : ℝ) * ((2 : ℝ) ^ (i + 1))⁻¹ :=
    fun i => mul_nonneg (Nat.cast_nonneg _) (by positivity)
  have hsum : Summable (fun n : ℕ => ((jsp87Level 1 n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) := by
    show Summable (jsp87BitTerm fun n => jsp87Level 1 n)
    exact summable_jsp87Level 1
  have hlow : (∑ i ∈ Finset.range 5, ((jsp87Level 1 i : ℕ) : ℝ) * ((2 : ℝ) ^ (i + 1))⁻¹)
      ≤ ∑' n : ℕ, ((jsp87Level 1 n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹ :=
    Summable.sum_le_tsum (Finset.range 5) (fun i _ => hnonneg i) hsum
  have hval : (∑ i ∈ Finset.range 5, ((jsp87Level 1 i : ℕ) : ℝ) * ((2 : ℝ) ^ (i + 1))⁻¹)
      = 1 / 8 + 1 / 16 + 1 / 32 := by
    have h0 : jsp87Level 1 0 = 0 := (jsp87Level_eq_zero_iff 1 0).2 (by simp)
    have h1 : jsp87Level 1 1 = 0 := (jsp87Level_eq_zero_iff 1 1).2 (by simp)
    have h2 : jsp87Level 1 2 = 1 := jsp87Level_eq_one_of_omega_eq (by native_decide)
    have h3 : jsp87Level 1 3 = 1 := jsp87Level_eq_one_of_omega_eq (by native_decide)
    have h4 : jsp87Level 1 4 = 1 := jsp87Level_eq_one_of_omega_eq (by native_decide)
    simp only [Finset.sum_range_succ_comm]
    norm_num [h0, h1, h2, h3, h4]
  have hlow' : (1 / 8 + 1 / 16 + 1 / 32 : ℝ)
      ≤ ∑' n : ℕ, ((jsp87Level 1 n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹ := by
    rwa [hval] at hlow
  have hres : jsp87LevelSeries 1 > 1 / 8 := by
    show (∑' n : ℕ, ((jsp87Level 1 n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) > 1 / 8
    linarith
  exact hres

/-- **THE "AT LEAST" SERIESES DECREASE**: `A (k+1) ≤ A k`.  Together with
`jsp87AtLeastSeries_one`, every "at least" series lies in `[0, 1/4]`. -/
theorem jsp87AtLeastSeries_antitone (k : ℕ) :
    jsp87AtLeastSeries (k + 1) ≤ jsp87AtLeastSeries k := by
  have hstep : ∀ n, ((jsp87AtLeast (k + 1) n : ℕ) : ℝ) ≤ ((jsp87AtLeast k n : ℕ) : ℝ) := by
    intro n
    by_cases hc : k + 1 ≤ omega n
    · have h1 := (jsp87AtLeast_eq_one_iff (k + 1) n).2 hc
      have h2 := (jsp87AtLeast_eq_one_iff k n).2 (Nat.le_of_lt (Nat.succ_le_iff.mp hc))
      rw [h1, h2]
    · have hlt' : omega n < k + 1 := by omega
      have h1 := (jsp87AtLeast_eq_zero_iff (k + 1) n).2 hlt'
      rw [h1]
      exact_mod_cast Nat.zero_le (jsp87AtLeast k n)
  have h1 : Summable (fun n : ℕ => ((jsp87AtLeast (k + 1) n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) := by
    show Summable (jsp87BitTerm fun n => jsp87AtLeast (k + 1) n)
    exact summable_jsp87AtLeast (k + 1)
  have h2 : Summable (fun n : ℕ => ((jsp87AtLeast k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) := by
    show Summable (jsp87BitTerm fun n => jsp87AtLeast k n)
    exact summable_jsp87AtLeast k
  have hle := Summable.tsum_le_tsum
    (fun n => mul_le_mul_of_nonneg_right (hstep n) (by positivity)) h1 h2
  have hres : jsp87BinarySeries (fun n => jsp87AtLeast (k + 1) n)
      ≤ jsp87BinarySeries (fun n => jsp87AtLeast k n) := by
    unfold jsp87BinarySeries
    exact hle
  exact hres

/-! ## 6. The level decomposition of the Erdős series -/

/-- **`A 1 ≤ S`.**  Every `n ≥ 2` has at least one prime factor, so the "at least
one" series is dominated termwise by the Erdős series.  This is the level
decomposition's first level, and it reproduces the bound `1/4 ≤ S` by a new
route (round 47 obtained it from the partial sum over `n < 5`). -/
theorem jsp87AtLeastSeries_one_le_S : 1 / 4 ≤ jsp87Series := by
  rw [← jsp87AtLeastSeries_one]
  have hstep : ∀ n, ((jsp87AtLeast 1 n : ℕ) : ℝ) ≤ ((omega n : ℕ) : ℝ) := by
    intro n
    by_cases h2 : 1 ≤ omega n
    · rw [(jsp87AtLeast_eq_one_iff 1 n).2 h2]
      exact_mod_cast h2
    · have hlt : omega n < 1 := by omega
      have h0 : jsp87AtLeast 1 n = 0 := (jsp87AtLeast_eq_zero_iff 1 n).2 hlt
      rw [h0]
      exact_mod_cast Nat.zero_le (omega n)
  have h1 : Summable (fun n : ℕ => ((jsp87AtLeast 1 n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) := by
    show Summable (jsp87BitTerm fun n => jsp87AtLeast 1 n)
    exact summable_jsp87AtLeast 1
  have h2 : Summable (fun n : ℕ => ((omega n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) :=
    summable_omega_mul_inv_two_pow
  have hle := Summable.tsum_le_tsum
    (fun n => mul_le_mul_of_nonneg_right (hstep n) (by positivity)) h1 h2
  show jsp87BinarySeries (fun n => jsp87AtLeast 1 n) ≤ jsp87Series
  unfold jsp87BinarySeries
  exact hle

/-- **THE LEVEL SERIESES ARE DOMINATED BY THE "AT LEAST" SERIESES**:
`L k ≤ A k`, because `[ω n = k] ≤ [k ≤ ω n]` pointwise. -/
theorem jsp87LevelSeries_le_atLeast (k : ℕ) : jsp87LevelSeries k ≤ jsp87AtLeastSeries k := by
  have hstep : ∀ n, ((jsp87Level k n : ℕ) : ℝ) ≤ ((jsp87AtLeast k n : ℕ) : ℝ) := by
    intro n
    by_cases hc : omega n = k
    · rw [jsp87Level_eq_one_of_omega_eq hc, (jsp87AtLeast_eq_one_iff k n).2 (by omega)]
    · have h0 := jsp87Level_eq_zero_of_omega_ne hc
      rw [h0]
      exact_mod_cast Nat.zero_le (jsp87AtLeast k n)
  have h1 : Summable (fun n : ℕ => ((jsp87Level k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) := by
    show Summable (jsp87BitTerm fun n => jsp87Level k n)
    exact summable_jsp87Level k
  have h2 : Summable (fun n : ℕ => ((jsp87AtLeast k n : ℕ) : ℝ) * ((2 : ℝ) ^ (n + 1))⁻¹) := by
    show Summable (jsp87BitTerm fun n => jsp87AtLeast k n)
    exact summable_jsp87AtLeast k
  have hle := Summable.tsum_le_tsum
    (fun n => mul_le_mul_of_nonneg_right (hstep n) (by positivity)) h1 h2
  have hres : jsp87BinarySeries (fun n => jsp87Level k n)
      ≤ jsp87BinarySeries (fun n => jsp87AtLeast k n) := by
    unfold jsp87BinarySeries
    exact hle
  exact hres

/-- **EVERY "AT LEAST" SERIES IS STRICTLY POSITIVE**, and every one of them lies in
`[0, 1/4]` (`jsp87AtLeastSeries_one`, `jsp87AtLeastSeries_antitone`). -/
theorem jsp87AtLeastSeries_pos (k : ℕ) : 0 < jsp87AtLeastSeries k := by
  rcases Nat.eq_zero_or_pos k with h | h
  · rw [h, jsp87AtLeastSeries_zero]
    norm_num
  · have h1 := jsp87LevelSeries_pos k h
    have h2 := jsp87LevelSeries_le_atLeast k
    have hres : jsp87AtLeastSeries k > 0 := by linarith
    exact hres

/-- **AND EVERY ONE OF THEM IS BELOW `1/4`**, for `k ≥ 1`: `A 1 = 1/4` and `A` is
antitone. -/
theorem jsp87AtLeastSeries_le_one_quot (k : ℕ) (hk : 1 ≤ k) : jsp87AtLeastSeries k ≤ 1 / 4 := by
  induction k with
  | zero => omega
  | succ k ih =>
      have hone := jsp87AtLeastSeries_one
      rcases Nat.eq_zero_or_pos k with h | h
      · rw [h, hone]
      · have hmono := jsp87AtLeastSeries_antitone k
        exact hmono.trans (ih (by omega))

end JSP87
